FROM quay.io/sampandey001/secktor
RUN git clone https://github.com/Tharusha69/KING-VAJIRA-M /root/Tharusha69
WORKDIR /root/Tharusha69/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
